name: Generate Snake

on:
  schedule:
    # Ser√° atualizado a cada 5 horas
    - cron: "0 */5 * * *"

  # Permite executar manualmente na lista de Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks repo under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Gera os arquivos snake
      - uses: Platane/snk@v3
        with:
          github_user_name: biellil
          outputs: |
            dist/github-snake.svg?palette=github-dark&palette_light=github-light

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
